@startuml
title usecase11 **考试教室与时间安排**


[-> GUI : 登录系统（账号，密码）
activate GUI
create Login
GUI -> Login : create(用户)
activate Login
deactivate GUI

[-> GUI : 进入课表管理界面（）
activate GUI
GUI -> Course : 查询课程（学生）
activate Course
Course --> GUI : 返回结果（）
deactivate Course
GUI -> GUI : 展示课程信息（）
deactivate GUI

loop
[-> GUI : 提交考试信息（课程名单，考试信息）
activate GUI
create ExamTable
GUI -> ExamTable : create(课程名单，考试信息)
deactivate GUI
end

[-> GUI : 离开系统（）
activate GUI

GUI -> Login : delete（用户）
destroy Login
deactivate GUI
@enduml