@startuml
title usecase12 **考核形式申请**


[-> GUI : 登录系统（账号，密码）
activate GUI
create Login
GUI -> Login : create(用户)
activate Login
deactivate GUI

[-> GUI : 考核形式申请（申请信息）
activate GUI
create ExamFormApply
GUI -> ExamFormApply : create(申请信息)
deactivate GUI

[-> GUI : 离开系统（）
activate GUI

GUI -> Login : delete（用户）
destroy Login
deactivate GUI
@enduml