@startuml
title usecase16 **考试成绩复查**


[-> GUI : 登录系统（账号，密码）
activate GUI
create Login
GUI -> Login : create(用户)
activate Login
deactivate GUI

[-> GUI : 提出成绩复查申请（学生，课程，信息）
activate GUI
create ScoreReviewApply
GUI -> ScoreReviewApply : create(学生，课程，信息)
deactivate GUI

[-> GUI : 查询成绩复查申请状态（ScoreReviewApply）
activate GUI
GUI -> ScoreReviewApply : 查询状态（）
ScoreReviewApply --> GUI : 返回状态（）
deactivate GUI

[-> GUI : 离开系统（）
activate GUI

GUI -> Login : delete（用户）
destroy Login
deactivate GUI
@enduml