@startuml
title usecase19 **免修考试的申请与安排**


[-> GUI : 登录系统（账号，密码）
activate GUI
create Login
GUI -> Login : create(用户)
activate Login
deactivate GUI

[-> GUI : 提出免修申请（学生，课程，信息）
activate GUI
create NoStudyApply
GUI -> NoStudyApply : create(学生，课程，信息)
deactivate GUI

[-> GUI : 查询免修申请状态（课程）
activate GUI
GUI -> NoStudyApply : 查询状态()
activate NoStudyApply
NoStudyApply --> GUI : 返回状态()
deactivate NoStudyApply
deactivate GUI

[-> GUI : 离开系统（）
activate GUI

GUI -> Login : delete（用户）
destroy Login
deactivate GUI
@enduml