@startuml
title usecase18 **补考信息发布**


[-> GUI : 登录系统（账号，密码）
activate GUI
create Login
GUI -> Login : create(用户)
deactivate GUI

[-> GUI : 进入补考发布界面（）
activate GUI
deactivate GUI

loop
[-> GUI : 查看考表（课程）
activate GUI
GUI -> ExamTable : 查看考表（课程）
activate ExamTable
ExamTable --> GUI : 返回结果（）
deactivate ExamTable
deactivate GUI
end

[-> GUI : 离开系统（）
activate GUI

GUI -> Login : delete（用户）
destroy Login
deactivate GUI
@enduml